address/urls.py
from . import views
from django.urls import path


app_name = "address"
urlpatterns = [
    path('', views.login, name="login"),

    path('signup', views.signup, name="signup"),

    path('address-book', views.address_book, name="address_book"),

    path('add-address', views.add_address, name="add_address"),

    path('view-address/<int:id>', views.view_address, name="view_address"),

    path('edit-address/<int:edit_id>', views.edit_address, name="edit_address"),

    path('logout', views.logout, name="logout"),

    path('search', views.search, name="search"),

    path('geo', views.test1, name="geo"),
]

addressbook/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('address.urls')),
]+static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

address/models.py
import email
from django.db import models

# Create your models here.

class Register(models.Model):  
    username=models.CharField(max_length=100)
    email=models.CharField(max_length=100)
    password=models.CharField(max_length=100)

    class Meta:
        db_table='register'

class AddAddress(models.Model):
    user_id=models.ForeignKey(Register,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product/')
    username=models.CharField(max_length=120)
    number=models.CharField(max_length=20)
    email_id=models.CharField(max_length=150)
    place=models.CharField(max_length=100)
    address=models.CharField(max_length=100)

    class Meta:
        db_table='add_address'

address/views.py
from ast import Add
from atexit import register
from re import M
from django.shortcuts import render, redirect
from . models import AddAddress, Register
from . decorator import auth_user
from django.db.models import Q
import json


def signup(request):
    msg = ''
    if request.method == 'POST':
        reg_username = request.POST['regname']
        reg_email = request.POST['regemail']
        reg_password = request.POST['regpass']

        user_exist = Register.objects.filter(email=reg_email)

        if user_exist:
            msg = "Email already exist"
        else:
            register = Register(username=reg_username,
                                email=reg_email, password=reg_password)
            register.save()
            return redirect('address:login')
    return render(request, 'address/signup.html', {'msg': msg, })


def login(request):
    msg = ''
    if request.method == 'POST':
        log_email = request.POST['logemail']
        log_password = request.POST['logpass']

        user_exist = Register.objects.filter(
            email=log_email, password=log_password).exists()

        if user_exist:
            user_detail = Register.objects.get(
                email=log_email, password=log_password)
            request.session['user_id'] = user_detail.id
            return redirect("address:address_book")
        else:
            msg = 'invalid email or password'

    return render(request, 'address/login.html', {'err_msg': msg, })


@auth_user
def address_book(request):
    address_book = AddAddress.objects.filter(
        user_id=request.session['user_id'])

    return render(request, 'address/address_book.html', {'address': address_book, })


@auth_user
def add_address(request):
    msg = ""
    if request.method == 'POST':

        image = request.FILES['image']
        username = request.POST['uname']
        phone = request.POST['phone']
        email_id = request.POST['email']
        place = request.POST['place']
        address = request.POST['address']

        userid = Register.objects.get(id=request.session['user_id'])
        
        add_address = AddAddress(user_id=userid, image=image, username=username,
                                 number=phone, email_id=email_id, place=place, address=address)
        add_address.save()
        return redirect('address:address_book')

    if request.method == 'GET':
        return render(request, 'address/add_address.html')


@auth_user
def view_address(request, id):
    view_address = AddAddress.objects.get(id=id)

    if request.method == 'POST':

        address_id = request.POST['view_id']
        address = AddAddress.objects.get(id=address_id)
        address.delete()
        return redirect('address:address_book')

    return render(request, 'address/view_address.html', {'view_address': view_address, })


@auth_user
def edit_address(request, edit_id):
    edit_address = AddAddress.objects.get(id=edit_id)

    if request.method == 'POST':
        if 'image' in request.FILES:
            image = request.FILES['image']
        else:
            image = edit_address.image

        username = request.POST['uname']
        phone = request.POST['phone']
        email_id = request.POST['email']
        place = request.POST['place']
        address = request.POST['address']

        edit_address.image = image
        edit_address.username = username
        edit_address.number = phone
        edit_address.email_id = email_id
        edit_address.place = place
        edit_address.address = address
        edit_address.save()

        return redirect("address:address_book")
    return render(request, 'address/edit_address.html', {'edit_address': edit_address})


@auth_user
def search(request):

    if request.method == 'GET':
        user_name = request.GET.get('search')
        status = AddAddress.objects.filter(
            Q(username__icontains=user_name) | Q(address__icontains=user_name))
        return render(request, "address/search.html", {"username": status, })

    return render(request, "address/search.html")


def logout(request):
    del request.session['user_id']
    request.session.flush()
    return redirect('address:login')


def test1(request):

    return render(request, "address/test_geo_coordinates.html")


def web_entities_include_geo_results(path):
    """Detects web annotations given an image, using the geotag metadata
    in the image to detect web entities."""
    from google.cloud import vision
    import io
    client = vision.ImageAnnotatorClient()

    with io.open(path, 'rb') as image_file:
        content = image_file.read()

    image = vision.Image(content=content)

    web_detection_params = vision.WebDetectionParams(
        include_geo_results=True)
    image_context = vision.ImageContext(
        web_detection_params=web_detection_params)

    response = client.web_detection(image=image, image_context=image_context)

    for entity in response.web_detection.web_entities:
        print('\n\tScore      : {}'.format(entity.score))
        print(u'\tDescription: {}'.format(entity.description))

    if response.error.message:
        raise Exception(
            '{}\nFor more info on error messages, check: '
            'https://cloud.google.com/apis/design/errors'.format(
                response.error.message))

address/templates/address/add_address.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <!-- custom css -->
  <link rel="stylesheet" href="{% static 'css/add_address.css' %}" />

  <!-- bootstrap css v4.6.1 -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous" />

  <!-- font awesome css -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
  <!-- font awesome js -->
  <script src="https://your-site-or-cdn.com/fontawesome/v6.1.1/js/all.js" data-auto-replace-svg="nest"></script>

  <title>Add Address</title>
</head>

<body>
  <!-- Header start -->
  <nav class="navbar navbar-expand-lg navbar-light bg-secondary">

    <a href="{% url 'address:address_book' %}">
      <h3 class="navbar-brand">ADDRESS BOOK</h3>
    </a>
    
  </nav>
  <!-- Header end -->


  <!-- Content body start -->
  <div id="main-wrapper">
    <div class="content-body">
      <div class="container-fluid">
        <form action="" method="POST" onsubmit="return validate();" enctype="multipart/form-data">
          {% csrf_token %}

          <!-- Image Field input -->
          <div class="upload" style="margin-top: 3%">
            <img id="img"  src="{% static 'images/noprofile.jpg' %}" width="100" height="100" alt="" />
            <div class="round">
              <input type="file" id="image" name="image" required />
              <i class="fa fa-camera" style="color: #fff"></i>
            </div>
          </div>
          <div class="form-group text-center">
            <small id="image_err"></small>
          </div>

          <!-- Name input -->
          <div class="form-group">
            <label for="name">Full Name</label>
            <input type="text" class="form-control" id="uname" name="uname" placeholder="Full Name*" />
            <small id="name_err"></small>
          </div>

          <!-- Phone Number input -->
          <div class="form-group">
            <label for="number">Phone Number</label>
            <input type="text" class="form-control" id="phone" name="phone" placeholder="Phone Number*" />
            <small id="phone_err"></small>
          </div>

          <!-- Email id input -->
          <div class="form-group">
            <label for="email">Email</label>
            <input type="text" class="form-control" aria-describedby="emailHelp" id="email" name="email"
              placeholder="E-Mail*" />
            <small id="email_err"></small>
          </div>

          <!-- Place input -->
          <div class="form-group">
            <label for="place">Place</label>
            <input type="text" class="form-control" id="place" name="place" placeholder="Place*" />
            <small id="place_err"></small>
          </div>

          <!-- Address input -->
          <div class="form-group">
            <label for="address">Address</label>
            <textarea class="form-control" id="address" name="address" rows="3"></textarea>
            <small id="address_err"></small>

            <small style="color: green">{{msg}}</small>
            <small style="color: red">{{msg1}}</small>
          </div>

          <!-- Register button -->
          <button type="submit" class="btn btn-primary">Register</button>
        </form>
      </div>
    </div>
  </div>
  <!-- Content body end -->


  <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDSfs8umRCxomZSNp2fXHpHvX4ju4WEkHo&callback=initAutocomplete&libraries=places&v=weekly"
    defer></script>

  <script>
    // This sample uses the Places Autocomplete widget to:
    // 1. Help the user select a place
    // 2. Retrieve the address components associated with that place
    // 3. Populate the form fields with those address components.
    // This sample requires the Places library, Maps JavaScript API.
    // Include the libraries=places parameter when you first load the API.
    // For example: <script
    // src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAvXE2sx_Xp0zinLtxJRo7DeNwhklESERI&libraries=places">
    let autocomplete;
    let address1Field;
    let address2Field;
    // let postalField;

    function initAutocomplete() {
      address1Field = document.querySelector("#place");
      address2Field = document.querySelector("#address");
      // postalField = document.querySelector("#postcode");
      // Create the autocomplete object, restricting the search predictions to
      // addresses in the US and Canada.
      autocomplete = new google.maps.places.Autocomplete(address1Field, {
        componentRestrictions: { country: ["us", "ca"] },
        fields: ["address_components", "geometry"],
        types: ["address"],
      });
      address1Field.focus();
      // When the user selects an address from the drop-down, populate the
      // address fields in the form.
      autocomplete.addListener("place_changed", fillInAddress);
    }

    function fillInAddress() {
      // Get the place details from the autocomplete object.
      const place = autocomplete.getPlace();
      let address1 = "";
      // let postcode = "";

      // Get each component of the address from the place details,
      // and then fill-in the corresponding field on the form.
      // place.address_components are google.maps.GeocoderAddressComponent objects
      // which are documented at http://goo.gle/3l5i5Mr
      for (const component of place.address_components) {
        // @ts-ignore remove once typings fixed
        const componentType = component.types[0];

        switch (componentType) {
          case "street_number": {
            address1 = `${component.long_name} ${address1}`;
            break;
          }

          case "route": {
            address1 += component.short_name;
            break;
          }

          // case "postal_code": {
          //   postcode = `${component.long_name}${postcode}`;
          //   break;
          // }

          // case "postal_code_suffix": {
          //   postcode = `${postcode}-${component.long_name}`;
          //   break;
          // }
          // case "locality":
          //   document.querySelector("#locality").value = component.long_name;
          //   break;
          // case "administrative_area_level_1": {
          //   document.querySelector("#state").value = component.short_name;
          //   break;
          // }
          // case "country":
          // document.querySelector("#country").value = component.long_name;
          // break;
        }
      }

      address1Field.value = address1;
      // postalField.value = postcode;
      // After filling the form with address components from the Autocomplete
      // prediction, set cursor focus on the second address line to encourage
      // entry of subpremise information such as apartment, unit, or floor number.
      address2Field.focus();
    }

    window.initAutocomplete = initAutocomplete;
  </script>

  <script src="{% static 'js/address_validation.js' %}"></script>

</body>

</html>

address/templates/address/address_book.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Address Book</title>

  <!-- custom css -->
  <link rel="stylesheet" href="{% static 'css/address.css' %}" />
   <!-- custom css -->
   <link rel="stylesheet" href="{% static 'css/address_book_file.css' %}" />

  <!-- bootstrap v4.6.1 css -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous" />
  <!-- bootstrap 3.3.7 js  -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <!-- bootstrap 4.6.1 js  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- jquery js -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
</head>

<body>
  <!-- Header start -->
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">

      <h3 class="navbar-brand">ADDRESS BOOK</h3>

      <div class="collapse navbar-collapse" id="navbarNav"></div>

      <center>
        <div class="container">
          <div class="row">
            <div class="col-md-12">

              <form action="{% url 'address:search' %}" method="GET">

                <!-- Search bar -->
              <div class="input-group" id="boot-search-box">

                <input type="text" name="search" class="form-control" placeholder="Search" />

                <button type="submit"  class="btn btn-primary">
                  search
                </button>

              </div>
              </form>      
            </div>
          </div>
        
      </center>
      <!-- Add button -->
      <a class="float-right btn btn-sm btn-success" href="{% url 'address:add_address' %}"><i
          class="fa fa-plus"></i></a>
      <div style="padding-left: 14px">
        <!-- Logout button -->
        <a href="{% url 'address:logout' %}" class="float-right btn btn-info btn-sm">
          <span class="glyphicon glyphicon-log-out"></span> Log out
        </a>
      </div>

    </nav>
    <!-- Header end -->
  
    <!-- Content body start -->
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% if address %} {% for a in address %}
    <a class="acard" href="{% url 'address:view_address' a.id %}">
      <div class="card p-1 text-center">
        <blockquote class="blockquote mb-0" style="text-align: center">
          <!-- Image field -->
          <div class="upload float-left">
            <img src="media/{{ a.image }}" width="100" height="100" alt="" />
          </div>

          <div class="float-left text-left" style="padding-left: 15px; padding-top: 2 px">
            <h5>{{ a.username }}</h5>
            <h5>{{ a.number }}</h5>
            <h5>{{ a.email_id }}</h5>
          </div>
        </blockquote>
      </div>
    </a>
    {% endfor %} {% else %}
    <div class="text-center">
      <strong style="color: red; background-color: black">There are no records at the moment. You can save address by
        tapping
        the + button</strong>
    </div>
    {% endif %}
  </form>
  <!-- Content body end -->
</body>

</html>

address/templates/address/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/login.css' %}" />

    <!-- bootstrap v4.6.1 -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
      integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
      crossorigin="anonymous"
    />
   

  </head>
  
  <body>
    
    <!-- Header start -->
    <nav>

    <div id="hf" class="child">ADDRESS BOOK</div>

  </nav>
  <!-- Header end -->

  <!-- Content body start -->
    <div class="pdt">
      
      <form
        action=""
        method="POST"
        style="width: 50%; border: 1px solid #ccc; padding: 20px"
      >
        {% csrf_token %}

        <center>
          <h2 class="pdb">Login</h2>
        </center>

        <!-- Username input -->
        <div class="form-outline mb-4">
          <input
            type="text"
            name="logemail"
            id="logemail"
            class="form-control"
            placeholder="Email"
          />
        </div>

        <!-- Password input -->
        <div class="form-outline mb-4">
          <input
            type="password"
            name="logpass"
            id="logpass"
            class="form-control"
            placeholder="Password"
          />
        </div>
        <small style="color: red">{{err_msg}}</small>

        <!-- 2 column grid layout for inline styling -->
        <div class="row mb-4">
          <div class="col">
            <!-- Simple link -->
            <a href="">Forgot password?</a>
          </div>
        </div>

        <!-- Submit button -->
        <button type="submit" class="btn btn-primary btn-block mb-4">
          Login
        </button>

        <!-- Register buttons -->
        <div class="text-center">
          <p style="color: black;">Not a member? <a href="{% url 'address:signup' %}">Register</a></p>
        </div>
      </form>
    </div>
  </body>
</html>

address/templates/address/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Search Result</title>

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/address.css' %}" />
    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/address_book_file.css' %}" />

    <!-- bootstrap css v4.6.1 -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
      integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn"
      crossorigin="anonymous"
    />
    <!-- bootstrap css v3.3.7 -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
    />

    <!-- bootstrap js v3.3.7 -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- font awesome css -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- font awesome js -->
    <script
      src="https://your-site-or-cdn.com/fontawesome/v6.1.1/js/all.js"
      data-auto-replace-svg="nest"
    ></script>

    <!-- font -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round"
      rel="stylesheet"
    />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- pdf script -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js"></script>
  </head>
  <body>
    <!-- header start -->
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
      <a href="{% url 'address:address_book' %}">
        <h3 class="navbar-brand">ADDRESS BOOK</h3>
      </a>
    </nav>
    <!-- Header end -->

    <!-- Content body start -->
    {% if username %}
    <div style="color: rgb(255, 0, 0)">
      <h2>Search Result</h2>
    </div>
    {% endif %}

    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %} {% if username %} {% for user in username %}

      <a class="acard" href="{% url 'address:view_address' user.id %}">
        <div class="card p-1 text-center">
          <blockquote class="blockquote mb-0" style="text-align: center">
            <!-- Image field -->
            <div class="upload float-left">
              <img
                src="media/{{ user.image }}"
                width="100"
                height="100"
                alt=""
              />
            </div>

            <div
              class="float-left text-left"
              style="padding-left: 15px; padding-top: 3px"
            >
              <h5>{{ user.username }}</h5>
              <h5>{{ user.number }}</h5>
              <h5>{{ user.email_id }}</h5>
            </div>
          </blockquote>
        </div>
      </a>

      {% endfor %} {% else %}
      <div class="text-center">
        <strong style="color: red; background-color: black"
          >There are no records at the moment.
        </strong>
      </div>
      {% endif %}
    </form>
  </body>
</html>

address/templates/address/view_address.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View Address</title>

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'css/view_address.css' %}" />

    <!-- bootstrap css v4.6.1 css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <!-- bootstrap css v3.3.7 css -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- bootstrap js v3.3.7 js -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <!-- font awesome css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- font awesome js -->
    <script src="https://your-site-or-cdn.com/fontawesome/v6.1.1/js/all.js" data-auto-replace-svg="nest"></script>

    <!-- font -->
    <link href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- pdf script -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.4/jspdf.debug.js"></script>

</head>
<body>

    <!-- header start -->
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">

        <div style="width: 100%;">

            <a href="{% url 'address:address_book' %}">
                <h3 style="margin: 0;" class="navbar-brand">ADDRESS BOOK</h3>
            </a>

            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="text-right " style=" font-size: 25px; ">

                    <!-- Edit button -->
                    <a href="{% url 'address:edit_address' view_address.id %}" style="color: black;"><button type="button"><i
                                class="fa fa-pencil"></i></button></a>

                    <!-- Delete button -->
                    <button type="submit"><i class="fa fa-trash"></i></button>

                    <input type="hidden" name="view_id" value="{{view_address.id}}" id="">

                </div>
        </div>

    </nav>
    <!-- Header end -->

    <!-- Content body start -->
    <div id="test">

        <!-- image field input -->
        <div class="upload" style=" width: 200px; height: 200px; padding-top: 10px;">

            <img src="/media/{{view_address.image}}" width=200 height=200 alt="">

        </div>

        <center>
            <div>
                <h2 hidden>Name</h2>
                <h2 style="color: black; ">{{view_address.username|upper}}</h2>
            </div>
        </center>

        <!-- Detailes section start -->
        <div class="container" style="background-color: rgb(221, 221, 221); display: block; ">

            <br>

            <!-- Phone number detailes -->
            <div style="display: flex; font-size: 25px;">

                <div style="padding-right: 20px; width: 40px;"><i class="fa fa-mobile"></i> </div>
                <div>
                    <h3 hidden>Phone</h3>{{view_address.number}}
                </div>
            </div>

            <br>

            <!-- Email detailes -->
            <div style="display: flex; font-size: 25px;">

                <div style="padding-right: 20px; width: 40px;"><i class="fa fa-envelope-o"></i></div>
                <div>
                    <h3 hidden>Email</h3>{{view_address.email_id}}
                </div>
            </div>

            <br>

            <!-- Address detailes -->
            <div style="display: flex; font-size: 25px;">

                <div style="padding-right: 20px; width: 40px;"><i class="fa fa-address-card"></i></i> </div>
                <div>
                    <h3 hidden>Address</h3>{{view_address.address}}
                </div>
            </div>

            <br>

            <!-- Place detailes -->
            <div style="display: flex; font-size: 25px;">

                <div style="padding-right: 20px; width: 40px;"><i class="fa fa-location-arrow"></i></i> </div>
                <div>
                    <h3 hidden>place</h3>{{view_address.place}}
                </div>
            </div>
            <br>

        </div>
        <!-- Detailes session end -->

        </form>

    </div>

    <!-- Pdf download button  -->
    <div class="text-center" style="padding-top: 5px;">
        <a href="javascript:generatePDF()"><button class="btn btn-primary">Dowload PDF</button></a>
    </div>

    <script>
        function generatePDF() {
            var doc = new jsPDF();  //create jsPDF object
            doc.fromHTML(document.getElementById("test"), // page element which you want to print as PDF
                15,
                15,
                {
                    'width': 170  //set width
                },
                function (a) {
                    doc.save("HTML2PDF.pdf"); // save file name as HTML2PDF.pdf
                });
        }
    </script>

</body>
</html>